/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Intern;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for InternControllerApi
 */
@Disabled
public class InternControllerApiTest {

    private final InternControllerApi api = new InternControllerApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createInternsTest() throws ApiException {
        Intern intern = null;
        api.createInterns(intern);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteInternsTest() throws ApiException {
        Long id = null;
        api.deleteInterns(id);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getInternsTest() throws ApiException {
        List<Intern> response = api.getInterns();
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateInternsTest() throws ApiException {
        Long id = null;
        Intern intern = null;
        api.updateInterns(id, intern);
        // TODO: test validations
    }

}
