/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.Attendance;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AttendanceDto
 */
public class AttendanceDtoTest {
    private final AttendanceDto model = new AttendanceDto();

    /**
     * Model tests for AttendanceDto
     */
    @Test
    public void testAttendanceDto() {
        // TODO: test AttendanceDto
    }

    /**
     * Test the property 'attendanceList'
     */
    @Test
    public void attendanceListTest() {
        // TODO: test attendanceList
    }

    /**
     * Test the property 'attendancePercentage'
     */
    @Test
    public void attendancePercentageTest() {
        // TODO: test attendancePercentage
    }

}
