/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.AttendanceDto;
import org.openapitools.client.model.FeedbackDto;
import org.openapitools.client.model.Intern;
import org.openapitools.client.model.TaskCompletionDto;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for InternHistoryDTO
 */
public class InternHistoryDTOTest {
    private final InternHistoryDTO model = new InternHistoryDTO();

    /**
     * Model tests for InternHistoryDTO
     */
    @Test
    public void testInternHistoryDTO() {
        // TODO: test InternHistoryDTO
    }

    /**
     * Test the property 'intern'
     */
    @Test
    public void internTest() {
        // TODO: test intern
    }

    /**
     * Test the property 'attendanceRecords'
     */
    @Test
    public void attendanceRecordsTest() {
        // TODO: test attendanceRecords
    }

    /**
     * Test the property 'taskCompletions'
     */
    @Test
    public void taskCompletionsTest() {
        // TODO: test taskCompletions
    }

    /**
     * Test the property 'feedbacks'
     */
    @Test
    public void feedbacksTest() {
        // TODO: test feedbacks
    }

}
