/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.InternEntity;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for InternsControllerApi
 */
@Disabled
public class InternsControllerApiTest {

    private final InternsControllerApi api = new InternsControllerApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void addInternsTest() throws ApiException {
        InternEntity internEntity = null;
        InternEntity response = api.addInterns(internEntity);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteInternTest() throws ApiException {
        Long id = null;
        api.deleteIntern(id);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAllTest() throws ApiException {
        List<InternEntity> response = api.getAll();
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateInternTest() throws ApiException {
        Long id = null;
        InternEntity internEntity = null;
        InternEntity response = api.updateIntern(id, internEntity);
        // TODO: test validations
    }

}
