openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- description: Generated server url
  url: http://localhost:8080
paths:
  /update:
    put:
      operationId: updatedIntern
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Intern'
        required: true
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Intern'
          description: OK
      tags:
      - intern-controller
      x-content-type: application/json
      x-accepts:
      - '*/*'
  /create:
    post:
      operationId: saveIntern
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Intern'
        required: true
      responses:
        "200":
          description: OK
      tags:
      - intern-controller
      x-content-type: application/json
      x-accepts:
      - application/json
  /get:
    get:
      operationId: readIntern
      responses:
        "200":
          content:
            '*/*':
              schema:
                items:
                  $ref: '#/components/schemas/Intern'
                type: array
          description: OK
      tags:
      - intern-controller
      x-accepts:
      - '*/*'
  /delete:
    delete:
      operationId: deletedIntern
      parameters: []
      responses:
        "200":
          description: OK
      tags:
      - intern-controller
      x-accepts:
      - application/json
components:
  schemas:
    Intern:
      example:
        name: name
        id: 0
        age: 6
      properties:
        id:
          format: int64
          type: integer
        name:
          type: string
        age:
          format: int32
          type: integer
      type: object

