/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Intern;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for InternControllApi
 */
@Disabled
public class InternControllApiTest {

    private final InternControllApi api = new InternControllApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createTest() throws ApiException {
        Intern intern = null;
        api.create(intern);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteTest() throws ApiException {
        Long id = null;
        Intern response = api.delete(id);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void readTest() throws ApiException {
        List<Intern> response = api.read();
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateTest() throws ApiException {
        Long id = null;
        Intern intern = null;
        Intern response = api.update(id, intern);
        // TODO: test validations
    }

}
