/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Intern
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-10-24T18:53:47.115704800+05:30[Asia/Calcutta]", comments = "Generator version: 7.9.0")
public class Intern {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Long id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_PERFORMANCE_SCORE = "performanceScore";
  @SerializedName(SERIALIZED_NAME_PERFORMANCE_SCORE)
  private Double performanceScore;

  public static final String SERIALIZED_NAME_TASK_PROGRESS = "taskProgress";
  @SerializedName(SERIALIZED_NAME_TASK_PROGRESS)
  private String taskProgress;

  public Intern() {
  }

  public Intern id(Long id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }


  public Intern name(String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  public Intern performanceScore(Double performanceScore) {
    this.performanceScore = performanceScore;
    return this;
  }

  /**
   * Get performanceScore
   * @return performanceScore
   */
  @javax.annotation.Nullable
  public Double getPerformanceScore() {
    return performanceScore;
  }

  public void setPerformanceScore(Double performanceScore) {
    this.performanceScore = performanceScore;
  }


  public Intern taskProgress(String taskProgress) {
    this.taskProgress = taskProgress;
    return this;
  }

  /**
   * Get taskProgress
   * @return taskProgress
   */
  @javax.annotation.Nullable
  public String getTaskProgress() {
    return taskProgress;
  }

  public void setTaskProgress(String taskProgress) {
    this.taskProgress = taskProgress;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Intern intern = (Intern) o;
    return Objects.equals(this.id, intern.id) &&
        Objects.equals(this.name, intern.name) &&
        Objects.equals(this.performanceScore, intern.performanceScore) &&
        Objects.equals(this.taskProgress, intern.taskProgress);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, performanceScore, taskProgress);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Intern {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    performanceScore: ").append(toIndentedString(performanceScore)).append("\n");
    sb.append("    taskProgress: ").append(toIndentedString(taskProgress)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("name");
    openapiFields.add("performanceScore");
    openapiFields.add("taskProgress");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Intern
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Intern.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Intern is not found in the empty JSON string", Intern.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Intern.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `Intern` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("taskProgress") != null && !jsonObj.get("taskProgress").isJsonNull()) && !jsonObj.get("taskProgress").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `taskProgress` to be a primitive type in the JSON string but got `%s`", jsonObj.get("taskProgress").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Intern.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Intern' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Intern> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Intern.class));

       return (TypeAdapter<T>) new TypeAdapter<Intern>() {
           @Override
           public void write(JsonWriter out, Intern value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Intern read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Intern given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Intern
   * @throws IOException if the JSON string is invalid with respect to Intern
   */
  public static Intern fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Intern.class);
  }

  /**
   * Convert an instance of Intern to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

