version: '3.8'
services:
  app:
    image: mcr.microsoft.com/devcontainers/java:17  # Use Java 17 or your required version
    build:
      context: .
    volumes:
      - ..:/workspace:cached
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/mentaldimension
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mentaldimension
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
