/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * QuestionEntity
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-10-24T15:14:22.773044700+05:30[Asia/Calcutta]", comments = "Generator version: 7.9.0")
public class QuestionEntity {
  public static final String SERIALIZED_NAME_QUESTION_NUMBER = "questionNumber";
  @SerializedName(SERIALIZED_NAME_QUESTION_NUMBER)
  private Long questionNumber;

  public static final String SERIALIZED_NAME_POINTS = "points";
  @SerializedName(SERIALIZED_NAME_POINTS)
  private Integer points;

  public static final String SERIALIZED_NAME_QUESTIONS = "questions";
  @SerializedName(SERIALIZED_NAME_QUESTIONS)
  private String questions;

  public static final String SERIALIZED_NAME_ANSWERS = "answers";
  @SerializedName(SERIALIZED_NAME_ANSWERS)
  private String answers;

  public QuestionEntity() {
  }

  public QuestionEntity questionNumber(Long questionNumber) {
    this.questionNumber = questionNumber;
    return this;
  }

  /**
   * Get questionNumber
   * @return questionNumber
   */
  @javax.annotation.Nullable
  public Long getQuestionNumber() {
    return questionNumber;
  }

  public void setQuestionNumber(Long questionNumber) {
    this.questionNumber = questionNumber;
  }


  public QuestionEntity points(Integer points) {
    this.points = points;
    return this;
  }

  /**
   * Get points
   * @return points
   */
  @javax.annotation.Nullable
  public Integer getPoints() {
    return points;
  }

  public void setPoints(Integer points) {
    this.points = points;
  }


  public QuestionEntity questions(String questions) {
    this.questions = questions;
    return this;
  }

  /**
   * Get questions
   * @return questions
   */
  @javax.annotation.Nullable
  public String getQuestions() {
    return questions;
  }

  public void setQuestions(String questions) {
    this.questions = questions;
  }


  public QuestionEntity answers(String answers) {
    this.answers = answers;
    return this;
  }

  /**
   * Get answers
   * @return answers
   */
  @javax.annotation.Nullable
  public String getAnswers() {
    return answers;
  }

  public void setAnswers(String answers) {
    this.answers = answers;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QuestionEntity questionEntity = (QuestionEntity) o;
    return Objects.equals(this.questionNumber, questionEntity.questionNumber) &&
        Objects.equals(this.points, questionEntity.points) &&
        Objects.equals(this.questions, questionEntity.questions) &&
        Objects.equals(this.answers, questionEntity.answers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(questionNumber, points, questions, answers);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QuestionEntity {\n");
    sb.append("    questionNumber: ").append(toIndentedString(questionNumber)).append("\n");
    sb.append("    points: ").append(toIndentedString(points)).append("\n");
    sb.append("    questions: ").append(toIndentedString(questions)).append("\n");
    sb.append("    answers: ").append(toIndentedString(answers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("questionNumber");
    openapiFields.add("points");
    openapiFields.add("questions");
    openapiFields.add("answers");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to QuestionEntity
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!QuestionEntity.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in QuestionEntity is not found in the empty JSON string", QuestionEntity.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!QuestionEntity.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `QuestionEntity` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("questions") != null && !jsonObj.get("questions").isJsonNull()) && !jsonObj.get("questions").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `questions` to be a primitive type in the JSON string but got `%s`", jsonObj.get("questions").toString()));
      }
      if ((jsonObj.get("answers") != null && !jsonObj.get("answers").isJsonNull()) && !jsonObj.get("answers").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `answers` to be a primitive type in the JSON string but got `%s`", jsonObj.get("answers").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!QuestionEntity.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'QuestionEntity' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<QuestionEntity> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(QuestionEntity.class));

       return (TypeAdapter<T>) new TypeAdapter<QuestionEntity>() {
           @Override
           public void write(JsonWriter out, QuestionEntity value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public QuestionEntity read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of QuestionEntity given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of QuestionEntity
   * @throws IOException if the JSON string is invalid with respect to QuestionEntity
   */
  public static QuestionEntity fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, QuestionEntity.class);
  }

  /**
   * Convert an instance of QuestionEntity to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

