/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for BalancedScoreCardEntity
 */
public class BalancedScoreCardEntityTest {
    private final BalancedScoreCardEntity model = new BalancedScoreCardEntity();

    /**
     * Model tests for BalancedScoreCardEntity
     */
    @Test
    public void testBalancedScoreCardEntity() {
        // TODO: test BalancedScoreCardEntity
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'rankPosition'
     */
    @Test
    public void rankPositionTest() {
        // TODO: test rankPosition
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'emailId'
     */
    @Test
    public void emailIdTest() {
        // TODO: test emailId
    }

    /**
     * Test the property 'aadhaarNumber'
     */
    @Test
    public void aadhaarNumberTest() {
        // TODO: test aadhaarNumber
    }

    /**
     * Test the property 'pan'
     */
    @Test
    public void panTest() {
        // TODO: test pan
    }

    /**
     * Test the property 'totalAnalizedScore'
     */
    @Test
    public void totalAnalizedScoreTest() {
        // TODO: test totalAnalizedScore
    }

    /**
     * Test the property 'physicalScore'
     */
    @Test
    public void physicalScoreTest() {
        // TODO: test physicalScore
    }

    /**
     * Test the property 'mentalInvolvement'
     */
    @Test
    public void mentalInvolvementTest() {
        // TODO: test mentalInvolvement
    }

    /**
     * Test the property 'socialInvolvement'
     */
    @Test
    public void socialInvolvementTest() {
        // TODO: test socialInvolvement
    }

    /**
     * Test the property 'spiritualInvolvement'
     */
    @Test
    public void spiritualInvolvementTest() {
        // TODO: test spiritualInvolvement
    }

    /**
     * Test the property 'rewardsEarned'
     */
    @Test
    public void rewardsEarnedTest() {
        // TODO: test rewardsEarned
    }

}
