/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.CognitiveWorkshop;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CognitiveWorkshopControllerApi
 */
@Disabled
public class CognitiveWorkshopControllerApiTest {

    private final CognitiveWorkshopControllerApi api = new CognitiveWorkshopControllerApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void completeWorkshopTest() throws ApiException {
        Long id = null;
        CognitiveWorkshop response = api.completeWorkshop(id);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createWorkshopTest() throws ApiException {
        CognitiveWorkshop cognitiveWorkshop = null;
        CognitiveWorkshop response = api.createWorkshop(cognitiveWorkshop);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteAllWorkshopsTest() throws ApiException {
        api.deleteAllWorkshops();
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteWorkshopTest() throws ApiException {
        Long id = null;
        api.deleteWorkshop(id);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAllWorkshopsTest() throws ApiException {
        List<CognitiveWorkshop> response = api.getAllWorkshops();
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getWorkshopByIdTest() throws ApiException {
        Long id = null;
        CognitiveWorkshop response = api.getWorkshopById(id);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateWorkshopTest() throws ApiException {
        Long id = null;
        CognitiveWorkshop cognitiveWorkshop = null;
        CognitiveWorkshop response = api.updateWorkshop(id, cognitiveWorkshop);
        // TODO: test validations
    }

}
