/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.MCQQuestion;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for McqQuestionControllerApi
 */
@Disabled
public class McqQuestionControllerApiTest {

    private final McqQuestionControllerApi api = new McqQuestionControllerApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createQuestionTest() throws ApiException {
        MCQQuestion mcQQuestion = null;
        MCQQuestion response = api.createQuestion(mcQQuestion);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteAllQuestionsTest() throws ApiException {
        api.deleteAllQuestions();
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteQuestionTest() throws ApiException {
        Long id = null;
        api.deleteQuestion(id);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAllQuestionsTest() throws ApiException {
        List<MCQQuestion> response = api.getAllQuestions();
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getQuestionByIdTest() throws ApiException {
        Long id = null;
        MCQQuestion response = api.getQuestionById(id);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void submitAnswerTest() throws ApiException {
        Long id = null;
        String body = null;
        String response = api.submitAnswer(id, body);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateQuestionTest() throws ApiException {
        Long id = null;
        MCQQuestion mcQQuestion = null;
        MCQQuestion response = api.updateQuestion(id, mcQQuestion);
        // TODO: test validations
    }

}
