/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for QuestionEntity
 */
public class QuestionEntityTest {
    private final QuestionEntity model = new QuestionEntity();

    /**
     * Model tests for QuestionEntity
     */
    @Test
    public void testQuestionEntity() {
        // TODO: test QuestionEntity
    }

    /**
     * Test the property 'questionNumber'
     */
    @Test
    public void questionNumberTest() {
        // TODO: test questionNumber
    }

    /**
     * Test the property 'points'
     */
    @Test
    public void pointsTest() {
        // TODO: test points
    }

    /**
     * Test the property 'questions'
     */
    @Test
    public void questionsTest() {
        // TODO: test questions
    }

    /**
     * Test the property 'answers'
     */
    @Test
    public void answersTest() {
        // TODO: test answers
    }

}
