/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Attendance;
import org.openapitools.client.model.AttendanceDto;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AttendanceControllerApi
 */
@Disabled
public class AttendanceControllerApiTest {

    private final AttendanceControllerApi api = new AttendanceControllerApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createAttendanceTest() throws ApiException {
        Long internId = null;
        Attendance attendance = null;
        Attendance response = api.createAttendance(internId, attendance);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAttendanceByInternIdTest() throws ApiException {
        Long internId = null;
        AttendanceDto response = api.getAttendanceByInternId(internId);
        // TODO: test validations
    }

}
