/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Feedback;
import org.openapitools.client.model.FeedbackDto;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for FeedbackControllerApi
 */
@Disabled
public class FeedbackControllerApiTest {

    private final FeedbackControllerApi api = new FeedbackControllerApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createFeedbacksTest() throws ApiException {
        Long internId = null;
        List<Feedback> feedback = null;
        List<Feedback> response = api.createFeedbacks(internId, feedback);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getFeedbackByInternIdTest() throws ApiException {
        Long internId = null;
        FeedbackDto response = api.getFeedbackByInternId(internId);
        // TODO: test validations
    }

}
