/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Intern;
import org.openapitools.client.model.InternHistoryDTO;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for InternControllerApi
 */
@Disabled
public class InternControllerApiTest {

    private final InternControllerApi api = new InternControllerApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createInternTest() throws ApiException {
        Intern intern = null;
        Intern response = api.createIntern(intern);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteInternTest() throws ApiException {
        Long internId = null;
        api.deleteIntern(internId);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAllInternsTest() throws ApiException {
        List<Intern> response = api.getAllInterns();
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getInternByIdTest() throws ApiException {
        Long internId = null;
        Intern response = api.getInternById(internId);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getInternHistoryTest() throws ApiException {
        Long internId = null;
        InternHistoryDTO response = api.getInternHistory(internId);
        // TODO: test validations
    }

}
