/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.Attendance;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * AttendanceDto
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-01T19:18:12.247642800+05:30[Asia/Calcutta]", comments = "Generator version: 7.9.0")
public class AttendanceDto {
  public static final String SERIALIZED_NAME_ATTENDANCE_LIST = "attendanceList";
  @SerializedName(SERIALIZED_NAME_ATTENDANCE_LIST)
  private List<Attendance> attendanceList = new ArrayList<>();

  public static final String SERIALIZED_NAME_ATTENDANCE_PERCENTAGE = "attendancePercentage";
  @SerializedName(SERIALIZED_NAME_ATTENDANCE_PERCENTAGE)
  private Double attendancePercentage;

  public AttendanceDto() {
  }

  public AttendanceDto attendanceList(List<Attendance> attendanceList) {
    this.attendanceList = attendanceList;
    return this;
  }

  public AttendanceDto addAttendanceListItem(Attendance attendanceListItem) {
    if (this.attendanceList == null) {
      this.attendanceList = new ArrayList<>();
    }
    this.attendanceList.add(attendanceListItem);
    return this;
  }

  /**
   * Get attendanceList
   * @return attendanceList
   */
  @javax.annotation.Nullable
  public List<Attendance> getAttendanceList() {
    return attendanceList;
  }

  public void setAttendanceList(List<Attendance> attendanceList) {
    this.attendanceList = attendanceList;
  }


  public AttendanceDto attendancePercentage(Double attendancePercentage) {
    this.attendancePercentage = attendancePercentage;
    return this;
  }

  /**
   * Get attendancePercentage
   * @return attendancePercentage
   */
  @javax.annotation.Nullable
  public Double getAttendancePercentage() {
    return attendancePercentage;
  }

  public void setAttendancePercentage(Double attendancePercentage) {
    this.attendancePercentage = attendancePercentage;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AttendanceDto attendanceDto = (AttendanceDto) o;
    return Objects.equals(this.attendanceList, attendanceDto.attendanceList) &&
        Objects.equals(this.attendancePercentage, attendanceDto.attendancePercentage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(attendanceList, attendancePercentage);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AttendanceDto {\n");
    sb.append("    attendanceList: ").append(toIndentedString(attendanceList)).append("\n");
    sb.append("    attendancePercentage: ").append(toIndentedString(attendancePercentage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("attendanceList");
    openapiFields.add("attendancePercentage");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to AttendanceDto
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AttendanceDto.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in AttendanceDto is not found in the empty JSON string", AttendanceDto.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!AttendanceDto.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `AttendanceDto` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("attendanceList") != null && !jsonObj.get("attendanceList").isJsonNull()) {
        JsonArray jsonArrayattendanceList = jsonObj.getAsJsonArray("attendanceList");
        if (jsonArrayattendanceList != null) {
          // ensure the json data is an array
          if (!jsonObj.get("attendanceList").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `attendanceList` to be an array in the JSON string but got `%s`", jsonObj.get("attendanceList").toString()));
          }

          // validate the optional field `attendanceList` (array)
          for (int i = 0; i < jsonArrayattendanceList.size(); i++) {
            Attendance.validateJsonElement(jsonArrayattendanceList.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AttendanceDto.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AttendanceDto' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AttendanceDto> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AttendanceDto.class));

       return (TypeAdapter<T>) new TypeAdapter<AttendanceDto>() {
           @Override
           public void write(JsonWriter out, AttendanceDto value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AttendanceDto read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of AttendanceDto given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of AttendanceDto
   * @throws IOException if the JSON string is invalid with respect to AttendanceDto
   */
  public static AttendanceDto fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AttendanceDto.class);
  }

  /**
   * Convert an instance of AttendanceDto to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

