/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.Feedback;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * FeedbackDto
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-01T19:18:12.247642800+05:30[Asia/Calcutta]", comments = "Generator version: 7.9.0")
public class FeedbackDto {
  public static final String SERIALIZED_NAME_FEEDBACK_LIST = "feedbackList";
  @SerializedName(SERIALIZED_NAME_FEEDBACK_LIST)
  private List<Feedback> feedbackList = new ArrayList<>();

  public static final String SERIALIZED_NAME_AVERAGE_RATING = "averageRating";
  @SerializedName(SERIALIZED_NAME_AVERAGE_RATING)
  private Double averageRating;

  public FeedbackDto() {
  }

  public FeedbackDto feedbackList(List<Feedback> feedbackList) {
    this.feedbackList = feedbackList;
    return this;
  }

  public FeedbackDto addFeedbackListItem(Feedback feedbackListItem) {
    if (this.feedbackList == null) {
      this.feedbackList = new ArrayList<>();
    }
    this.feedbackList.add(feedbackListItem);
    return this;
  }

  /**
   * Get feedbackList
   * @return feedbackList
   */
  @javax.annotation.Nullable
  public List<Feedback> getFeedbackList() {
    return feedbackList;
  }

  public void setFeedbackList(List<Feedback> feedbackList) {
    this.feedbackList = feedbackList;
  }


  public FeedbackDto averageRating(Double averageRating) {
    this.averageRating = averageRating;
    return this;
  }

  /**
   * Get averageRating
   * @return averageRating
   */
  @javax.annotation.Nullable
  public Double getAverageRating() {
    return averageRating;
  }

  public void setAverageRating(Double averageRating) {
    this.averageRating = averageRating;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FeedbackDto feedbackDto = (FeedbackDto) o;
    return Objects.equals(this.feedbackList, feedbackDto.feedbackList) &&
        Objects.equals(this.averageRating, feedbackDto.averageRating);
  }

  @Override
  public int hashCode() {
    return Objects.hash(feedbackList, averageRating);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FeedbackDto {\n");
    sb.append("    feedbackList: ").append(toIndentedString(feedbackList)).append("\n");
    sb.append("    averageRating: ").append(toIndentedString(averageRating)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("feedbackList");
    openapiFields.add("averageRating");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to FeedbackDto
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!FeedbackDto.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in FeedbackDto is not found in the empty JSON string", FeedbackDto.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!FeedbackDto.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `FeedbackDto` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("feedbackList") != null && !jsonObj.get("feedbackList").isJsonNull()) {
        JsonArray jsonArrayfeedbackList = jsonObj.getAsJsonArray("feedbackList");
        if (jsonArrayfeedbackList != null) {
          // ensure the json data is an array
          if (!jsonObj.get("feedbackList").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `feedbackList` to be an array in the JSON string but got `%s`", jsonObj.get("feedbackList").toString()));
          }

          // validate the optional field `feedbackList` (array)
          for (int i = 0; i < jsonArrayfeedbackList.size(); i++) {
            Feedback.validateJsonElement(jsonArrayfeedbackList.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!FeedbackDto.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'FeedbackDto' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<FeedbackDto> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(FeedbackDto.class));

       return (TypeAdapter<T>) new TypeAdapter<FeedbackDto>() {
           @Override
           public void write(JsonWriter out, FeedbackDto value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public FeedbackDto read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of FeedbackDto given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of FeedbackDto
   * @throws IOException if the JSON string is invalid with respect to FeedbackDto
   */
  public static FeedbackDto fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, FeedbackDto.class);
  }

  /**
   * Convert an instance of FeedbackDto to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

