/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.AttendanceDto;
import org.openapitools.client.model.FeedbackDto;
import org.openapitools.client.model.Intern;
import org.openapitools.client.model.TaskCompletionDto;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * InternHistoryDTO
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-01T19:18:12.247642800+05:30[Asia/Calcutta]", comments = "Generator version: 7.9.0")
public class InternHistoryDTO {
  public static final String SERIALIZED_NAME_INTERN = "intern";
  @SerializedName(SERIALIZED_NAME_INTERN)
  private Intern intern;

  public static final String SERIALIZED_NAME_ATTENDANCE_RECORDS = "attendanceRecords";
  @SerializedName(SERIALIZED_NAME_ATTENDANCE_RECORDS)
  private AttendanceDto attendanceRecords;

  public static final String SERIALIZED_NAME_TASK_COMPLETIONS = "taskCompletions";
  @SerializedName(SERIALIZED_NAME_TASK_COMPLETIONS)
  private TaskCompletionDto taskCompletions;

  public static final String SERIALIZED_NAME_FEEDBACKS = "feedbacks";
  @SerializedName(SERIALIZED_NAME_FEEDBACKS)
  private FeedbackDto feedbacks;

  public InternHistoryDTO() {
  }

  public InternHistoryDTO intern(Intern intern) {
    this.intern = intern;
    return this;
  }

  /**
   * Get intern
   * @return intern
   */
  @javax.annotation.Nullable
  public Intern getIntern() {
    return intern;
  }

  public void setIntern(Intern intern) {
    this.intern = intern;
  }


  public InternHistoryDTO attendanceRecords(AttendanceDto attendanceRecords) {
    this.attendanceRecords = attendanceRecords;
    return this;
  }

  /**
   * Get attendanceRecords
   * @return attendanceRecords
   */
  @javax.annotation.Nullable
  public AttendanceDto getAttendanceRecords() {
    return attendanceRecords;
  }

  public void setAttendanceRecords(AttendanceDto attendanceRecords) {
    this.attendanceRecords = attendanceRecords;
  }


  public InternHistoryDTO taskCompletions(TaskCompletionDto taskCompletions) {
    this.taskCompletions = taskCompletions;
    return this;
  }

  /**
   * Get taskCompletions
   * @return taskCompletions
   */
  @javax.annotation.Nullable
  public TaskCompletionDto getTaskCompletions() {
    return taskCompletions;
  }

  public void setTaskCompletions(TaskCompletionDto taskCompletions) {
    this.taskCompletions = taskCompletions;
  }


  public InternHistoryDTO feedbacks(FeedbackDto feedbacks) {
    this.feedbacks = feedbacks;
    return this;
  }

  /**
   * Get feedbacks
   * @return feedbacks
   */
  @javax.annotation.Nullable
  public FeedbackDto getFeedbacks() {
    return feedbacks;
  }

  public void setFeedbacks(FeedbackDto feedbacks) {
    this.feedbacks = feedbacks;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InternHistoryDTO internHistoryDTO = (InternHistoryDTO) o;
    return Objects.equals(this.intern, internHistoryDTO.intern) &&
        Objects.equals(this.attendanceRecords, internHistoryDTO.attendanceRecords) &&
        Objects.equals(this.taskCompletions, internHistoryDTO.taskCompletions) &&
        Objects.equals(this.feedbacks, internHistoryDTO.feedbacks);
  }

  @Override
  public int hashCode() {
    return Objects.hash(intern, attendanceRecords, taskCompletions, feedbacks);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InternHistoryDTO {\n");
    sb.append("    intern: ").append(toIndentedString(intern)).append("\n");
    sb.append("    attendanceRecords: ").append(toIndentedString(attendanceRecords)).append("\n");
    sb.append("    taskCompletions: ").append(toIndentedString(taskCompletions)).append("\n");
    sb.append("    feedbacks: ").append(toIndentedString(feedbacks)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("intern");
    openapiFields.add("attendanceRecords");
    openapiFields.add("taskCompletions");
    openapiFields.add("feedbacks");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to InternHistoryDTO
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!InternHistoryDTO.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in InternHistoryDTO is not found in the empty JSON string", InternHistoryDTO.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!InternHistoryDTO.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `InternHistoryDTO` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `intern`
      if (jsonObj.get("intern") != null && !jsonObj.get("intern").isJsonNull()) {
        Intern.validateJsonElement(jsonObj.get("intern"));
      }
      // validate the optional field `attendanceRecords`
      if (jsonObj.get("attendanceRecords") != null && !jsonObj.get("attendanceRecords").isJsonNull()) {
        AttendanceDto.validateJsonElement(jsonObj.get("attendanceRecords"));
      }
      // validate the optional field `taskCompletions`
      if (jsonObj.get("taskCompletions") != null && !jsonObj.get("taskCompletions").isJsonNull()) {
        TaskCompletionDto.validateJsonElement(jsonObj.get("taskCompletions"));
      }
      // validate the optional field `feedbacks`
      if (jsonObj.get("feedbacks") != null && !jsonObj.get("feedbacks").isJsonNull()) {
        FeedbackDto.validateJsonElement(jsonObj.get("feedbacks"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!InternHistoryDTO.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'InternHistoryDTO' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<InternHistoryDTO> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(InternHistoryDTO.class));

       return (TypeAdapter<T>) new TypeAdapter<InternHistoryDTO>() {
           @Override
           public void write(JsonWriter out, InternHistoryDTO value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public InternHistoryDTO read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of InternHistoryDTO given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of InternHistoryDTO
   * @throws IOException if the JSON string is invalid with respect to InternHistoryDTO
   */
  public static InternHistoryDTO fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, InternHistoryDTO.class);
  }

  /**
   * Convert an instance of InternHistoryDTO to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

