/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.TaskCompletion;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * TaskCompletionDto
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-01T19:18:12.247642800+05:30[Asia/Calcutta]", comments = "Generator version: 7.9.0")
public class TaskCompletionDto {
  public static final String SERIALIZED_NAME_COMPLETION_PERCENTAGE = "completionPercentage";
  @SerializedName(SERIALIZED_NAME_COMPLETION_PERCENTAGE)
  private Double completionPercentage;

  public static final String SERIALIZED_NAME_TASK_COMPLETION_LIST = "taskCompletionList";
  @SerializedName(SERIALIZED_NAME_TASK_COMPLETION_LIST)
  private List<TaskCompletion> taskCompletionList = new ArrayList<>();

  public TaskCompletionDto() {
  }

  public TaskCompletionDto completionPercentage(Double completionPercentage) {
    this.completionPercentage = completionPercentage;
    return this;
  }

  /**
   * Get completionPercentage
   * @return completionPercentage
   */
  @javax.annotation.Nullable
  public Double getCompletionPercentage() {
    return completionPercentage;
  }

  public void setCompletionPercentage(Double completionPercentage) {
    this.completionPercentage = completionPercentage;
  }


  public TaskCompletionDto taskCompletionList(List<TaskCompletion> taskCompletionList) {
    this.taskCompletionList = taskCompletionList;
    return this;
  }

  public TaskCompletionDto addTaskCompletionListItem(TaskCompletion taskCompletionListItem) {
    if (this.taskCompletionList == null) {
      this.taskCompletionList = new ArrayList<>();
    }
    this.taskCompletionList.add(taskCompletionListItem);
    return this;
  }

  /**
   * Get taskCompletionList
   * @return taskCompletionList
   */
  @javax.annotation.Nullable
  public List<TaskCompletion> getTaskCompletionList() {
    return taskCompletionList;
  }

  public void setTaskCompletionList(List<TaskCompletion> taskCompletionList) {
    this.taskCompletionList = taskCompletionList;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TaskCompletionDto taskCompletionDto = (TaskCompletionDto) o;
    return Objects.equals(this.completionPercentage, taskCompletionDto.completionPercentage) &&
        Objects.equals(this.taskCompletionList, taskCompletionDto.taskCompletionList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(completionPercentage, taskCompletionList);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TaskCompletionDto {\n");
    sb.append("    completionPercentage: ").append(toIndentedString(completionPercentage)).append("\n");
    sb.append("    taskCompletionList: ").append(toIndentedString(taskCompletionList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("completionPercentage");
    openapiFields.add("taskCompletionList");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to TaskCompletionDto
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TaskCompletionDto.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TaskCompletionDto is not found in the empty JSON string", TaskCompletionDto.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!TaskCompletionDto.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `TaskCompletionDto` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("taskCompletionList") != null && !jsonObj.get("taskCompletionList").isJsonNull()) {
        JsonArray jsonArraytaskCompletionList = jsonObj.getAsJsonArray("taskCompletionList");
        if (jsonArraytaskCompletionList != null) {
          // ensure the json data is an array
          if (!jsonObj.get("taskCompletionList").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `taskCompletionList` to be an array in the JSON string but got `%s`", jsonObj.get("taskCompletionList").toString()));
          }

          // validate the optional field `taskCompletionList` (array)
          for (int i = 0; i < jsonArraytaskCompletionList.size(); i++) {
            TaskCompletion.validateJsonElement(jsonArraytaskCompletionList.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TaskCompletionDto.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TaskCompletionDto' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TaskCompletionDto> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TaskCompletionDto.class));

       return (TypeAdapter<T>) new TypeAdapter<TaskCompletionDto>() {
           @Override
           public void write(JsonWriter out, TaskCompletionDto value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TaskCompletionDto read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of TaskCompletionDto given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of TaskCompletionDto
   * @throws IOException if the JSON string is invalid with respect to TaskCompletionDto
   */
  public static TaskCompletionDto fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TaskCompletionDto.class);
  }

  /**
   * Convert an instance of TaskCompletionDto to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

